// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Models;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20240926145418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ProductsApi.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 3333m,
                            ProductName = "IPhone 12"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 4444m,
                            ProductName = "IPhone 13"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            Price = 5555m,
                            ProductName = "IPhone 14"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 6666m,
                            ProductName = "IPhone 15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
